# Copyright (c) 2016-2023 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Hans' blog
site_url: https://hans-tsai.github.io/hans_blog/
site_author: Hans Tsai
site_description: >-
  This is my technical blog. For taking learning notes and sharing my experience.

# Repository
repo_name: hans-tsai/hans_blog
repo_url: https://github.com/Hans-Tsai/hans_blog

# Copyright
copyright: Copyright &copy; 2023 ~ Hans Tsai

# Configuration
theme:
  language: zh-TW
  name: material
  custom_dir: material/.overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Poppins
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Hooks
hooks:
  - material/.overrides/hooks/translations.py

# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  generator: false  #刪除頁尾顯示“使用 MkDocs 材料製造”
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hans-tsai

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      title: 目錄
      permalink: true
      # toc_depth: 6
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true # 顯示程式語言名稱
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Programming language:
    - Node.js: programming_language/nodejs.md
    - Java: programming_language/java.md
  - Backend:
    - Framework:
      - Spring Boot: backend/framework/spring_boot.md
    - System Design:
      - DDD: backend/system_design/ddd.md
  - Cloud:
    - AWS:
      - SAA: cloud/aws/saa.md
  - Version Control:
    - Git: version_control/git.md
  - Coding Interview:
    - Geeks for Geeks:
      - DSA Tutorial: coding_interview/geeks_for_geeks/dsa_tutorial.md
    - LeetCode:
      - LeetCode 75: coding_interview/leetcode/leetcode75.md
    - NeetCode:
      - Blind 75: coding_interview/neetcode/blind75/blind75.md
      - Core skills:
        - Data Structure: coding_interview/neetcode/core_skills/data_structure.md
        - Algorithm: coding_interview/neetcode/core_skills/algorithm.md
        - Design Pattern: coding_interview/neetcode/core_skills/design_pattern.md
    - Tech interview handbook:
      - Coding interview preparation: coding_interview/tech_interview_handbook/blind75.md
      # - System design interview preparation
      # - Behavioral interview preparation
  - MkDocs Info:
    - MkDocs: mkdocs_info/mkdocs.md
